package com.example.spring.mvc.hibernate.entity;
// Generated 03/29/2025 5:57:28 p. m. by Hibernate Tools 6.5.1.Final

/**
 * Access generated by hbm2java
 */
public class Access implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private int idAccess;
	private Users users;
	private String password;
	private String oldPassword;

	public Access() {
	}

	public Access(int idAccess, Users users, String password, String oldPassword) {
		this.idAccess = idAccess;
		this.users = users;
		this.password = password;
		this.oldPassword = oldPassword;
	}

	public int getIdAccess() {
		return this.idAccess;
	}

	public void setIdAccess(int idAccess) {
		this.idAccess = idAccess;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getOldPassword() {
		return this.oldPassword;
	}

	public void setOldPassword(String oldPassword) {
		this.oldPassword = oldPassword;
	}

}
