package com.example.spring.mvc.hibernate.entity;
// Generated 03/29/2025 5:57:28 p. m. by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	private int idUser;
	private String email;
	private String firstName;
	private String lastName;
	@SuppressWarnings("rawtypes")
	private Set accesses = new HashSet(0);

	public Users() {
	}

	public Users(int idUser, String email, String firstName, String lastName) {
		this.idUser = idUser;
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	@SuppressWarnings("rawtypes")
	public Users(int idUser, String email, String firstName, String lastName, Set accesses) {
		this.idUser = idUser;
		this.email = email;
		this.firstName = firstName;
		this.lastName = lastName;
		this.accesses = accesses;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@SuppressWarnings("rawtypes")
	public Set getAccesses() {
		return this.accesses;
	}

	@SuppressWarnings("rawtypes")
	public void setAccesses(Set accesses) {
		this.accesses = accesses;
	}

}
