DROP TABLE IF EXISTS ACCESS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
 ID_USER      INTEGER      AUTO_INCREMENT,
 EMAIL        VARCHAR(100) NOT NULL,
 FIRST_NAME   VARCHAR(50)  NOT NULL,
 LAST_NAME    VARCHAR(50)  NOT NULL,
 PRIMARY KEY (ID_USER)
);

CREATE TABLE ACCESS (
 ID_ACCESS    INTEGER      AUTO_INCREMENT,
 ID_USER      INTEGER      NOT NULL,
 PASSWORD     VARCHAR(100) NOT NULL,
 OLD_PASSWORD VARCHAR(100),
 PRIMARY KEY (ID_ACCESS),
 FOREIGN KEY (ID_USER) REFERENCES USERS(ID_USER) ON DELETE CASCADE
);